---
version: "3.9"

networks:
  main:
    external: true
  back-tier:
  pi-hole_cloudflared:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.39.1
    restart: always
    user: 1000:1000
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - ping:ping
      - speedtest:speedtest
    networks:
      - back-tier
      - pi-hole_cloudflared

  trickster:
    image: tricksterio/trickster:2.0.0-beta2
    depends_on:
      - prometheus
    volumes:
      - ./trickster/config:/etc/trickster:ro
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana:9.2.2
    restart: always
    user: 1000:1000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - trickster
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - main

  ping:
    tty: true
    stdin_open: true
    expose:
      - 9115
    image: prom/blackbox-exporter
    restart: always
    volumes:
      - ./blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - back-tier

  speedtest:
    expose:
      - 9798
    image: miguelndecarvalho/speedtest-exporter
    restart: always
    networks:
      - back-tier

  nodeexp:
    privileged: true
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier

  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    expose:
      - 9617
    env_file:
      - pihole-exporter.env
    volumes:
      - ./certs:/etc/ssl/certs:ro
    restart: always
    networks:
      - back-tier
