{
 "title": "Pi stats",
 "description": "Raspberry pi performance",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "avg_time",
    "query": "1s,10s,30s,1m,2m,3m,4m,5m,10m,20m,30m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Pi CPU temp",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{}[${avg_time}])"
    }
   ]
  },
  {
   "title": "CPU scaling frequency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_cpu_scaling_frequency_hertz[${avg_time}]))/4"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[${avg_time}])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes[${avg_time}]) - (avg_over_time(node_memory_MemFree_bytes[${avg_time}]) + avg_over_time(node_memory_Cached_bytes[${avg_time}]) + avg_over_time(node_memory_Buffers_bytes[${avg_time}])) "
    }
   ]
  }
 ]
}