{
 "title": "PI-Hole Exporter",
 "description": "This is a PI-Hole dashboard when using the https://github.com/eko/pihole-exporter Prometheus exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(pihole_ads_blocked_today, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "🍓PI-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% of queries blocked",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(pihole_ads_blocked_today{hostname=\"$node\"}[5m])/rate(pihole_dns_queries_today{hostname=\"$node\"}[5m])*100",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_status{hostname='$node'}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{hostname='$node'}"
    },
    { "expr": "pihole_" }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_unique_domains{hostname='$node'}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{hostname='$node'}"
    }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pihole_querytypes{hostname=\"$node\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_top_ads{hostname='$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Query rate blocked/cached/forwarded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "queries/second" } },
   "targets": [
    {
     "expr": "rate(pihole_queries_cached{hostname='$node'}[30m])",
     "legendFormat": "Queries cached"
    },
    {
     "expr": "rate(pihole_queries_forwarded{hostname='$node'}[30m])",
     "legendFormat": "Queries forwarded"
    },
    {
     "expr": "rate(pihole_ads_blocked_today{hostname='$node'}[30m])",
     "legendFormat": "Queries blocked"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pihole_forward_destinations{hostname=~'$node'}",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_top_queries{hostname='$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Unique clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_unique_clients{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  }
 ]
}